BEGIN;

CREATE TABLE USERS(
	ID		SERIAL PRIMARY KEY,
	FIRST_NAME	VARCHAR(100),
	LAST_NAME	VARCHAR(100),
	EMAIL		VARCHAR(100)	UNIQUE,
	PASSWORD_HASH	VARCHAR(60)

);

CREATE TABLE SESSIONS(
	ACCESS_TOKEN		UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
--	REFRESH_TOKEN		TEXT,
	PROVIDER		VARCHAR(20) NOT NULL DEFAULT 'local' CHECK (PROVIDER IN ('local', 'google')),
	EXPIRES_AT		TIMESTAMP NOT NULL,
	CREATED_AT		TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

COMMIT;
